### ISSUE TITLE
error: lookup sql-db.service.cf.internal on 169.254.0.2:53: no such host

### ISSUE THREAD

**Issue by phong2tran** [cloudfoundry/cf-app-sd-release#4]
First thanks for making this early release available! This feature what we need for one of our CF deployment to enable one app (Docker container) to discover and talk to another app.  I just deployed cf-app-sd-release in our existing CF instance (deployed with cf-deployment).

I used use-bosh-dns.yml, use-bosh-dns-for-containers.yml, and enable-service-discovery.yml  from cf-deployment v1.9.0 and updated CF deployment to add the service discovery with this command (I left out other BOSH CLI options for brevity):

$ bosh -e bp-bosh -d cf deploy --no-redact cf-deployment/cf-deployment.yml \
    --vars-store env-repo/deployment-vars.yml \
    -o cf-deployment/operations/experimental/use-bosh-dns.yml \
    -o cf-deployment/operations/experimental/use-bosh-dns-for-containers.yml \
    -o cf-deployment/operations/experimental/enable-service-discovery.yml 

It failed on updating diego-api instance:

Task 2173 | 22:39:58 | Error: 'diego-api/4224b74e-0257-4da8-a0c4-1187ce6630a5 (0)' is not running after update. Review logs for failed jobs: bbs, silk-controller, locket

I sshed into the diego-api VM and checked the logs for these failed jobs (bbs, locket, silk-controller), I noticed these errors:

/var/vcap/sys/log$ tailf bbs/bbs.stdout.log
{"timestamp":"1516919285.177010775","source":"bbs","message":"bbs.starting","log_level":1,"data":{}}
{"timestamp":"1516919285.180291891","source":"bbs","message":"bbs.sql-failed-to-connect","log_level":3,"data":{"error":"dial tcp: lookup sql-db.service.cf.internal on 169.254.0.2:53: no such host","trace":"goroutine 1 [running]:\ncode.cloudfoundry.org/lager.(*logger).Fatal(0xc4200565a0, 0xdc4b9c, 0x15, 0x11f9ac0, 0xc420178190, 0x0, 0x0, 0x0)\n\t/var/vcap/packages/bbs/src/code.cloudfoundry.org/lager/logger.go:132 +0xca\nmain.main()\n\t/var/vcap/packages/bbs/src/code.cloudfoundry.org/bbs/cmd/bbs/main.go:164 +0x4bda\n"}}

/var/vcap/sys/log$ tailf locket/locket.stdout.log
{"timestamp":"1516918739.476332903","source":"locket","message":"locket.sql-failed-to-connect","log_level":3,"data":{"error":"dial tcp: lookup sql-db.service.cf.internal on 169.254.0.2:53: no such host","trace":"goroutine 1 [running]:\ncode.cloudfoundry.org/lager.(*logger).Fatal(0xc4201c6000, 0xa140a4, 0x15, 0xcd44c0, 0xc4200745f0, 0x0, 0x0, 0x0)\n\t/var/vcap/packages/locket/src/code.cloudfoundry.org/lager/logger.go:132 +0xca\nmain.main()\n\t/var/vcap/packages/locket/src/code.cloudfoundry.org/locket/cmd/locket/main.go:88 +0x1b3a\n"}}

/var/vcap/sys/log$ cat silk-controller/silk-controller.stderr.log
2018/01/25 21:43:38 cfnetworking.silk-controller error: connecting to database: unable to ping: dial tcp: lookup sql-db.service.cf.internal on 169.254.0.2:53: no such host
2018/01/25 21:45:09 cfnetworking.silk-controller error: connecting to database: unable to ping: dial tcp: lookup sql-db.service.cf.internal on 169.254.0.2:53: no such host
2018/01/25 21:46:49 cfnetworking.silk-controller error: connecting to database: unable to ping: dial tcp: lookup sql-db.service.cf.internal on 169.254.0.2:53: no such host

It looked like the local bosh-dns service (169.254.0.2:53) could not resolve the internal domain name for CF system component (sql-db.service.cf.internal). I also manually tested with dig and got no answer for the name:

$ dig @169.254.0.2 sql-db.service.cf.internal

; <<>> DiG 9.9.5-3ubuntu0.16-Ubuntu <<>> sql-db.service.cf.internal
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43290
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;sql-db.service.cf.internal.    IN      A

;; Query time: 0 msec
;; SERVER: 169.254.0.2#53(169.254.0.2)
;; WHEN: Thu Jan 25 22:49:18 UTC 2018
;; MSG SIZE  rcvd: 44

If we test name resolution through the local Consul agent, it's working:
$ dig @127.0.0.1 sql-db.service.cf.internal

; <<>> DiG 9.9.5-3ubuntu0.16-Ubuntu <<>> @127.0.0.1 sql-db.service.cf.internal
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22447
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;sql-db.service.cf.internal.    IN      A

;; ANSWER SECTION:
sql-db.service.cf.internal. 0   IN      A       10.9.56.16

I checked resolv.conf and 169.254.0.2 nameserver (bosh-dns) is coming before 127.0.0.1 nameserver (Consul DNS), so bosh-dns is used for DNS resolution on the VM.

$ cat /etc/resolv.conf
# This file was automatically updated by bosh-dns
nameserver 169.254.0.2

nameserver 127.0.0.1

I also tried to configure the bosh-dns recursors property (https://github.com/cloudfoundry/bosh-dns-release/blob/master/jobs/bosh-dns/spec#L93):
cat /var/vcap/jobs/bosh-dns/config/config.json | python -m json.tool
{
    "address": "169.254.0.2",
    "alias_files_glob": "/var/vcap/jobs/*/dns/aliases.json",
    "cache": {
        "enabled": false
    },
    "handlers_files_glob": "/var/vcap/jobs/*/dns/handlers.json",
    "health": {
        "ca_file": "config/certs/client_ca.crt",
        "certificate_file": "config/certs/client.crt",
        "check_interval": "20s",
        "enabled": false,
        "max_tracked_queries": 2000,
        "port": 8853,
        "private_key_file": "config/certs/client.key"
    },
    "port": 53,
    "records_file": "/var/vcap/instance/dns/records.json",
    "recursor_timeout": "2s",
    "recursors": [
        "127.0.0.1"
    ],
    "upcheck_domains": [
        "upcheck.bosh-dns."
    ]
}

I'm trying to see if bosh-dns will forward the DNS request to the Consul DNS (127.0.0.1) if it can not resolve the host name, but that did not help either. 

Here are the releases we used:
Release 'diego/1.28.0'
Release 'capi/1.47.0'
Release 'cf-networking/1.8.1'
Release 'bosh-dns/0.2.0' 
Release 'cf-app-sd/0.3.0' 

I also saw this document on BOSH DNS (https://bosh.io/docs/dns.html), but I'm not sure if we need to setup for our use case as we currently only need the service discovery (DNS-like resolution) for our apps/containers deployed on CF. Do we need to enable and configure this BOSH DNS as prerequisite for adding cf-app-sd-release?

Any suggestion on how to debug and fix this problem would be greatly appreciated. We definitely need to get the platform service discovery running on our CF.

**Comment by chefhoobajoob** [comment]
Question: what does the `scheduled` label mean for this issue?

**Comment by adobley** [comment]
@chefhoobajoob It means that it has been added to our backlog on Tracker

**Comment by joachimvaldez** [comment]
Yes, you do need BOSH DNS as a pre-requisite for cf-app-sd-release. Did you enable local DNS on your bosh director as specified [here](https://bosh.io/docs/dns.html)?

**Comment by phong2tran** [comment]
Thanks @joachimvaldez for the suggestion! After enabling the local BOSH DNS, I could successfully deploy the platform service discovery (cf-app-sd release) now without any error. Please add this as a prerequisite in How To Deploy instructions so other users would not run into this problem.

**Comment by chinangela** [comment]
@phong2tran great. We added this as a pre-requisite in the docs and are closing the issue.
