### ISSUE TITLE
Bosh Lite script: `route` doesn't exist on my Ubuntu machine

### ISSUE THREAD

**Issue by camelpunch** [cloudfoundry/cf-app-sd-release#5]
Was this meant to be something like:

```
sudo ip route add $ips via $gw
```

Or am I missing an executable?

**Comment by chinangela** [comment]
Hi @camelpunch yes, you are correct. `route` has been deprecated and replaced with `ip route`: https://dougvitale.wordpress.com/2011/12/21/deprecated-linux-networking-commands-and-their-replacements/#route

We updated the deploy script accordingly: 49fc0e9f9ccee20eddc5bb1578297068c20acc3d

Cheers,
Angela and @adobley

**Comment by camelpunch** [comment]
Thanks!
